#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 500Mi
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mysql
#spec:
#  selector:
#    matchLabels:
#      app: mysql
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: mysql
#    spec:
#      containers:
#        - name: mysql
#          image: mysql:8
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              value: password
#            - name: MYSQL_DATABASE
#              value: userDB
#          ports:
#            - containerPort: 3306
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: mysql-storage
#      volumes:
#        - name: mysql-storage
#          persistentVolumeClaim:
#            claimName: mysql-pvc
#      readinessProbe:
#        exec:
#          command:
#            - sh
#            - -c
#            - mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD
#        initialDelaySeconds: 15
#        periodSeconds: 5
#        livenessProbe:
#          exec:
#            command:
#              - sh
#              - -c
#              - mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD
#          initialDelaySeconds: 30
#          periodSeconds: 10
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql
#spec:
#  selector:
#    app: mysql
#  ports:
#    - port: 3306
#      targetPort: 3306
#  type: ClusterIP

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: userDB
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
