apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-serivce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-serivce
  template:
    metadata:
      labels:
        app: review-serivce
    spec:
      containers:
        - name: user
          image: rishika10442/review_serivce:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: review-serivce
spec:
  selector:
    app: review-serivce
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
