---
- name: Deploy Microservices to Kubernetes
  hosts: localhost
  become: false

  vars:
    dockerhub_user: "rishika10442"
    k8s_folder: "../k8s"
    services:
      - name: catalogue-service
      - name: user-service
      - name: order_service
      - name: borrow_service
      - name: review_serivce
      - name: gateway-service

  tasks:

    - name: Check if Minikube is running
      shell: minikube status
      register: minikube_status
      ignore_errors: true

    - name: Start Minikube if not running
      shell: minikube start --driver=docker
      when: "'host: Running' not in minikube_status.stdout"


    - name: Pull Docker images from Docker Hub
      shell: docker pull {{ dockerhub_user }}/{{ item.name }}:latest
      loop: "{{ services }}"
      register: docker_pull_output

    - name: Debug pulled images
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ docker_pull_output.results }}"

    - name: Apply Kubernetes YAML manifests
      shell: kubectl apply -f {{ k8s_folder }}
